packages:
  # pacakges
  - 'packages/eslint-config'
  - 'packages/tsdk'
  - 'packages/tsdk-express-adapter'
  - 'packages/tsdk-socket.io-adapter'
  - 'packages/tsdk-boilerplate'

  # website
  - 'website'

  # examples
  - 'examples/server'
  - 'examples/server/packages/fe-sdk-demo'
  - 'examples/web'
  - 'examples/app'
