packages:
  # pacakges
  - 'packages/eslint-config'
  - 'packages/tsdk'
  - 'packages/tsdk-server-adapters'
  - 'packages/tsdk-boilerplate'

  # website
  - 'website'

  # examples
  - 'examples/server'
  - 'examples/server/packages/fe-sdk-demo'
  - 'examples/server/packages/fe-sdk-demo/website'
  - 'examples/web'
  - 'examples/app'
