packages:
  # packages
  - 'packages/*'
  # exclude template
  - '!packages/tsdk/fe-sdk-template/**'

  # website
  - 'website'

  # examples
  - 'examples/**'
  # exclude dist projects
  - '!**/dist**'
