/**
 * This is auto generated by `tsdk`.
 * Don't edit this file.
 */

export * from './modules/todo/apiconf/AddTodo.apiconf';
export * from './modules/todo/apiconf/QueryTodo.apiconf';
export * from './modules/todo/apiconf/TodoSchema.apiconf';
export * from './modules/todo/apiconf/QueryTodoByCursor.apiconf';
export * from './modules/todo/apiconf/UpdateTodo.apiconf';
export * from './modules/todo/apiconf/DeleteTodo.apiconf';
