name: Windows CI

on:
  push:
    branches: ['main']
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run-on-windows-2019:
    runs-on: windows-2019

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        id: pnpm-install
        with:
          # version: 9.1.2
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - run: pnpm -v
      - run: dir
      # - run: pnpm lint
      - run: pnpm start:tsdk

      - uses: oven-sh/setup-bun@v2
      - run: pnpm start:bun

      - run: pnpm --filter fe-sdk-demo-docs build
      - run: dir
      
